version: '3'
services:
  web:
    image: php:7.4-apache
    ports:
      - '7777:80'
    volumes:
      - './public:/var/www/html'
    depends_on:
      - db
    working_dir: /var/www/
    platform: 'linux/x86_64'
  db:
    image: mysql:8.0
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: example
      MYSQL_USER: user
      MYSQL_PASSWORD: root
    platform: 'linux/x86_64'
    volumes:
      - './DBdata/:/var/lib/mysql'
  phpmyadmin:
    image: 'phpmyadmin/phpmyadmin'
    ports:
      - '1111:80'
    environment:
      PMA_HOST: db
      PMA_PORT: '3306'
    depends_on:
      - db
