version: '3'
services:
  web:
    image: php:7.4-apache
    ports:
      - '${WEB_PORT:-7777}:80'
    volumes:
      - './:/var/www/'
      - './infra/web/apache:/etc/apache2/sites-available/'
    depends_on:
      - db
    working_dir: /var/www/
    platform: 'linux/x86_64'
  db:
    image: mysql:8.0
    ports:
      - '${DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_NAME}'
      MYSQL_USER: '${DB_USER}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    platform: 'linux/x86_64'
    volumes:
      - './DBdata/:/var/lib/mysql'
  phpmyadmin:
    image: 'phpmyadmin/phpmyadmin'
    ports:
      - '1111:80'
    environment:
      PMA_HOST: '${DB_HOST}'
      PMA_PORT: '${DB_PORT:-3306}'
    depends_on:
      - db
